### ISSUE TITLE
xController and yController are bad details in desc

### ISSUE THREAD

**Issue by OriginalAndCreativeName** [Centennial-FTC-Robotics/Virus2019-2020#22]
Reason for splitting movement into x and y controller is so that we can compensate for different movement/dynamics/physics/whatever idk when the robot moves sideways vs when the robot moves forwards, meaning we have can have different values to control strafing movement, and different values to control forwards movement

xController and yController error is currently determined by the global x and global y variables

those global x and global y variables do not correspond to robot centric directions: ex, strafing becomes going forwards when rotated 90 degrees.

This causes a problem, as the x and y controller becomes flipped relative to the robot as heading changes, which defeats the purpose of having an x and y controller

**Comment by baconsuperguy** [comment]
It's added, and looks like testing went ok (aside from the bug in the vector class that was fixed)
